### ISSUE TITLE
I have a problem when I click the button

### ISSUE THREAD

**Issue by xXToXiiCDOGZz** [SmItH197/SteamAuthentication#171] opened 2017-02-16 21:17 UTC
So, my problem is that when I click the button (the login button), the site adds just ?login at the end of the url and the first line in index.php is: No OpenID Server found at http://steamcommunity.com/openid

What can I do? Thanks anyway

**Comment by minecraftinventz** [comment] 2017-04-13 13:09
Having same issue. Just adds  ?login

**Comment by nl-fell** [comment] 2017-09-10 14:15
Same here

**Comment by BlackCetha** [comment] 2017-09-10 15:41
Duplicate of #166.

**Closed** 2018-03-08 18:56 UTC
