### ISSUE TITLE
Get profile data

### ISSUE THREAD

**Issue by d3ancole1995** [SmItH197/SteamAuthentication#170] opened 2017-02-07 02:33 UTC
After setting up the script. It's not bringing anything back in the userInfo.php

I did some manual debugging and it seems that file_get_contents is not working (it's returning false), I changed this over to a simple curl call and it fixed it for me.

Not sure if this is an outstanding issue or if I have discovered something but I thought I would point it out.

Hope this helps and that it's not just me.

**Comment by BlackCetha** [comment] 2017-02-07 14:34
We are getting reports/requests like this every once in a while.
This is a problem with certain providers blocking `file_get_contents()`. But because it is easier to read and works in most cases we favour it over curl in the library.

Please close this 'issue'.

**Comment by timeisthelimit** [comment] 2017-07-15 17:15
Hi,

Since this isn't closed yet, I believe I'm having the same issue. Possibly the same issue. Anyway, I know the problem is somewhere in the userInfo.php file and this might be it. I'd say it's likely. I'm just not very literate in this part of web development and I'd like to try the solution proposed here to see if it works but I'm not sure which part of the code I need to change.

I'll keep trying myself until I get a reply but I'd appreciate any help I can get.

Thank you.

**Closed** 2017-08-30 13:09 UTC
