### ISSUE TITLE
works fine at localhost, stuck ?login at web domain

### ISSUE THREAD

**Issue by kekegod** [SmItH197/SteamAuthentication#107] opened 2016-02-16 22:16 UTC
as I write , it works perfectly fine at localhost, same file at the web domain doesnt work and stuck at ?login, 
this is how my code starts
<?php
require ('steamauth/steamauth.php');

**Comment by kekegod** [comment] 2016-02-16 23:33
guess its about domain , because now i tried it my webspace that university gave me , works fine there too

**Comment by bman46** [comment] 2016-02-17 00:40
try it with a different host service ex. Dot.tk it may be your host. If it still does not work with a different host, post your code

**Comment by bman46** [comment] 2016-02-17 22:02
and also when you used ur university's domain were you hosting it at university too?

**Comment by RedSparr0w** [comment] 2016-02-28 02:56
Fix for this is to remove `<!--Version 3.1--> ` from the start of the file

make sure file starts with 
```
<?php
require ('steamauth/steamauth.php'); 
?>
```

**Comment by bman46** [comment] 2016-02-28 03:12
That would not be the issue, this issue occurred way before the version # update

**Comment by bman46** [comment] 2016-02-28 03:14
And if that was the issue it would not work at his university

**Comment by RedSparr0w** [comment] 2016-02-28 03:27
I was only getting this error on my real website due to this, as it wouldn't update any header information.

Worked fine on my localhost test and c9.io test with the comment there but on my actual web host the comment broke it unless specified after sending header information

Sent from my iPhone

On 28/02/2016, at 4:14 pm, bman46 <notifications@github.com<mailto:notifications@github.com>> wrote:


And if that was the issue it would not work at his university

-

**Comment by bman46** [comment] 2016-02-28 03:36
So should we create a pull request to move it below the header or at the very bottom? It should be somewhere in the code because a lot of issues are caused by outdated code.

**Comment by RedSparr0w** [comment] 2016-02-28 03:47
heres the error message i get `Warning: Cannot modify header information - headers already sent`

i think bottom may have more advantage as it will ALWAYS be at the very bottom.
where as if its after stuff and people add more code then it can get pushed lower and lower

**Comment by SageNTitled** [comment] 2016-03-31 01:12
I can confirm that this is happening on version 3.1.1. Logging in works on localhost, but on my web server it gets stuck on the ?login URL. I don't know why this is happening...

**Comment by RedSparr0w** [comment] 2016-03-31 02:00
try enabling php error reporting and let us know what it spits out

**Comment by SageNTitled** [comment] 2016-03-31 02:21
Yeah, I narrowed it down to the headers. WordPress is apparently using headers, thus giving me the following error message: `Cannot send session cache limiter - headers already sent`

**Comment by RedSparr0w** [comment] 2016-03-31 02:25
do you happen to have [these lines](https://github.com/SmItH197/SteamAuthentication/blob/master/steamauth/steamauth.php#L37-L47) in your `steamauth.php` file?

as this should redirect even if headers already sent

**Comment by SageNTitled** [comment] 2016-03-31 02:27
Yes, that bit of code is present.

**Comment by RedSparr0w** [comment] 2016-03-31 02:35
Does the error code say anything about session_start like the following


Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at ............ on line *)

Sent from my iPhone

On 31/03/2016, at 3:28 pm, SageNTitled <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that bit of code is present.

-

**Comment by SageNTitled** [comment] 2016-03-31 02:38
Yes, it does.

**Comment by RedSparr0w** [comment] 2016-03-31 03:56
Any chance you could post the full error? Sorry for late replies financial year end today so very busy at work XD

Sent from my iPhone

On 31/03/2016, at 3:38 pm, SageNTitled <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, it does.

-

**Comment by SageNTitled** [comment] 2016-03-31 11:57
I fixed it. Recurring `<?php ?>` tags at the top of a template file was the villain. I was too tired to notice it yesterday I suppose...

Thanks for your time though.

**Comment by SmItH197** [comment] 2016-03-31 16:57
Closed!

**Closed by SmItH197** 2016-03-31 16:57 UTC
